### ISSUE TITLE
GH release deprecation notice

### ISSUE THREAD

**Issue by hadim** [regro/rever#239]
I receive this email from github:

> On November 5th, 2020 at 15:55 (UTC) you or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent github3.py/1.3.0.
> 
> We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication https://docs.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
> 
> You can learn more about these changes by visiting our developer blog https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/

Are you aware of that?

**Comment by scopatz** [comment]
OK we'll have to address that soon, then

**Comment by asmeurer** [comment]
This no longer works. You need to use something like the device authorization flow. You can reuse the GitHub_login() function from here https://github.com/drdoctr/doctr/pull/373.

**Comment by sbillinge** [comment]
Hi @scopatz et al.  @hadim thanks for the issue.  We are now bumping into this also.  Is there a resolution how to update the rever files to get this working again?  Thanks so much for this awesome software.

**Comment by asmeurer** [comment]
It may be possible to generate a token manually to use with rever.

**Comment by scopatz** [comment]
I just did a release today with rever. I am not sure what the fix is.  @asmeurer do you have a link?

**Comment by asmeurer** [comment]
See the links at https://github.com/drdoctr/doctr/issues/369. There are three options. I have an implementation at https://github.com/drdoctr/doctr/pull/373 that you should feel free to copy for the device authorization flow (just [this function](https://github.com/drdoctr/doctr/pull/373/files#diff-f99d32aee0d22598566ef794b3d93a2cad923ac5df96a56b61e4d62537b33d88R114), basically).

**Comment by hadim** [comment]
In case it can be useful, this GH python lib looks nice: https://ghapi.fast.ai/#How-to-use---Python

**Comment by rjkoch** [comment]
Hey, so it seems like in order to use the approach in the doctr fix, we would need a Device Authorization Grant, as per this page:
https://docs.github.com/en/developers/apps/authorizing-oauth-apps#device-flow


I am happy to do this if you all would like.

**Comment by hadim** [comment]
Yes please @rjkoch go ahead!

**Comment by rjkoch** [comment]
Cool, I've done this successfully. I can transfer the ownership of the app to a github username or organization. I certainly don't mind holding it, but users may feel more comfortable authorizing a more known user/org than myself.

I think I've got a functional fix in place and I'm working on testing things locally.

**Comment by hadim** [comment]
I haven't test #243 but if it fixes the issue, can someone release a new version of rever?

**Comment by rjkoch** [comment]
We're working on it, but [test_appimage.py](https://github.com/regro/rever/blob/16b9345b94d38aedb570af426d7ae135f7d69c12/tests/test_appimage.py) is failing during the release when testing in a docker container. I will put in a PR today to confirm this also happens in CI.  @anki-code I believe this is your feature. If the test can't be fixed we will likely remove the AppImage feature.

**Comment by anki-code** [comment]
> remove the AppImage feature.

The AppImage feature is used by [xonsh](https://gitter.im/xonsh/xonsh) and then `xonsh.AppImage` is used by another products like [xxh](https://github.com/xxh/xxh). I suggest to think twice about removing this.

How I can review the error?

**Comment by rjkoch** [comment]
The changelog is in the news documents. Nothing regarding AppImage has been changed. Only how rever interacts with GitHub has been changed.

To reproduce the error, clone/fork the repo and try to run `rever -a pytest`

**Comment by anki-code** [comment]
I'll take a look during the week. This could be probably the upstream error.

**Comment by anki-code** [comment]
Here is the upstream issue - https://github.com/niess/python-appimage/issues/31

**Comment by anki-code** [comment]
I've fixed the upstream issue in the Pull Request - https://github.com/niess/python-appimage/pull/32 - waiting for merge now.

The issue in the upstream package was related to the PyPi deprecation error:

> DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
pip 21.3 will remove support for this functionality. You can find discussion regarding this at pypa/pip#7555.

**Comment by anki-code** [comment]
@rjkoch the upstream PRs were merged and released, try to run rever tests again ;)

**Comment by rjkoch** [comment]
`rever -a pytest 0.50` still fail in [circleCI ](https://app.circleci.com/pipelines/github/regro/rever/111/workflows/7aa8c6da-2e9d-48cf-b859-6d74cc9ef78f/jobs/660) and locally for me

**Comment by rjkoch** [comment]
traceback:

`FAILED tests/test_appimage.py::test_appimage - SystemExit: 1
=================== 1 failed, 123 passed, 1 skipped in 9.75s ===================
activity-error:pytest:activity failed with exception:
Traceback (most recent call last):
  File "/home/circleci/miniconda/lib/python3.8/site-packages/rever/activity.xsh", line 83, in __call__
    self.func(*args, **kwargs)
  File "/home/circleci/miniconda/lib/python3.8/site-packages/rever/activities/pytest.xsh", line 27, in _func
    super()._func(code=command)
  File "/home/circleci/miniconda/lib/python3.8/site-packages/rever/activity.xsh", line 406, in _func
    rtn = docker.run_in_container(image, command, env=env, mounts=mounts)
  File "/home/circleci/miniconda/lib/python3.8/site-packages/rever/docker.xsh", line 450, in run_in_container
    ![docker run -t @(env_args) @(mount_args) @(image) @(command)]
  File "/home/circleci/miniconda/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 20899, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/home/circleci/miniconda/lib/python3.8/site-packages/xonsh/procs/__amalgam__.py", line 3497, in run_subproc
    command.end()
  File "/home/circleci/miniconda/lib/python3.8/site-packages/xonsh/procs/__amalgam__.py", line 907, in end
    self._end(tee_output=tee_output)
  File "/home/circleci/miniconda/lib/python3.8/site-packages/xonsh/procs/__amalgam__.py", line 926, in _end
    self._raise_subproc_error()
  File "/home/circleci/miniconda/lib/python3.8/site-packages/xonsh/procs/__amalgam__.py", line 1052, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['docker', 'run', '-t', '--env', 'VERSION=0.5.0', '--env', 'REVER_FORCED=False', '--env', 'PROJECT=rever', '--env', 'REVER_DIR=rever-tmp', '--env', 'ACTIVITIES=pytest', '--env', 'PYPI_SIGN=False', '--env', 'VERSION_BUMP_PATTERNS=[(\'rever/__init__.py\', \'__version__\\\\s*=.*\', "__version__ = \'$VERSION\'"), (\'setup.py\', \'version\\\\s*=.*,\', "version=\'$VERSION\',")]', '--env', 'CHANGELOG_FILENAME=CHANGELOG.rst', '--env', 'CHANGELOG_TEMPLATE=TEMPLATE.rst', '--env', 'PUSH_TAG_REMOTE=git@github.com:regro/rever.git', '--env', 'GITHUB_ORG=regro', '--env', 'GITHUB_REPO=rever', '--env', 'GHPAGES_REPO=git@github.com:regro/rever-docs.git', '--env', 'DOCKER_CONDA_DEPS=flake8,ruamel.yaml,coverage,prompt_toolkit,cloud_sptheme,pytest-cov,numpydoc,lazyasd,pytest-timeout,pytest,pprintpp,pytest-flake8,bibtexparser,codecov,xonsh>=0.9.20,github3.py,sphinx', '--env', 'DOCKER_APT_DEPS=file', '--env', 'DOCKER_INSTALL_COMMAND=git clean -fdx && ./setup.py install', '--env', 'DOCKER_GIT_NAME=rever', '--env', 'DOCKER_GIT_EMAIL=rever@example.com', '--env', 'RUNNING_ACTIVITIES=pytest', 'rever/rever-install', 'sh', '-c', 'pytest']' returned non-zero exit status 1.
rewinding to a7d7177268eb2232f5e326ee215394877b4f9305

Exited with code exit status 1`

**Comment by anki-code** [comment]
@rjkoch I can repeat the error by this commands (it would be cool if you gave this to me at start):

```python
cd /tmp
git clone https://github.com/regro/rever
cd rever
rever -a pytest 0.50
docker run -it --rm rever/rever-install bash
pytest tests/test_appimage.py
# RuntimeError: WARNING: Running pip as root will
```

So, PR is here - https://github.com/niess/python-appimage/pull/34 - waiting to merge.

**Comment by rjkoch** [comment]
@anki-code Great for the PR, hopefully this resolves our issue.

**Comment by anki-code** [comment]
@rjkoch the upstream PR was merged, let's try again!

**Comment by rjkoch** [comment]
@anki-code Thanks, trying it now.
